[build-system]
requires = ["setuptools", "setuptools-scm"]


[project]
name = "yogo"
description = "you only glance once?"
readme = "README.md"
requires-python = ">=3.7"
keywords = ["object detection", "YOLO", "deep learning", "Pytorch"]
dependencies = [
  "yaml",
  "torch",
  "torchvision",
  "tqdm",
  "wandb",
  "Pillow-SIMD"
]

[project.optional-dependencies]
onnx = ["onnx",
