name: format-check

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: x64
      - uses: psf/black@stable
        with:
          options: "--check"
          src: "./yogo ./tests"
