name: testing

on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install checking requirements
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install pytest==7.4.3
      - name: unittests :)
        run: pytest tests/
